services:
  - type: cron
    name: trading-bot-gap
    schedule: "*/5 * * * *"
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot-po3-eurusd.py
    envVars:
      - key: API_KEY
        value: ""
      - key: TELEGRAM_TOKEN
        value: ""
      - key: TELEGRAM_CHAT_IDS
        value: ""
